spring:
  datasource:
    url: jdbc:h2:mem:bookshelfdb
    username: sa
    password: pass
  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile:
        - prod
author:
  name: Birgit

bookshelf:
  something:
    - 5
    - 6
    - 7
    - 8